### ISSUE TITLE
Wrap around?

### ISSUE THREAD

**Issue by greigs** [thooyork/gameoflife3d#1]
This is great, I've added a bloom effect to my fork so it looks more like an LED panel cube. 
Do you think it would be possible to have the game of life wrap all around the cube, instead of a copy of one game on each side?

**Comment by greigs** [comment]
Working on it. I have 6 games rendering now and I think with an adjacency matrix will be enough to do the rest.

**Comment by greigs** [comment]
https://imgur.com/a/f3ZM34Y

**Comment by thooyork** [comment]
closed
